<!DOCTYPE html>
	<html lang="en">
	<head>
		<meta charset="UTF-8">
		<title>Usuarios</title>
		 <link href='//fonts.googleapis.com/css?family=Lato:300' rel='stylesheet' type='text/css'>
	        <style>
	            body {
	                margin: 50px 0 0 0;
	                padding: 0;
	                width: 100%;
	                font-family: "Helvetica Neue", Helvetica, Arial, sans-serif;
	                text-align: center;
	                color: #aaa;
	                font-size: 18px;
	            }
	            h1 {
	                color: #719e40;
	                letter-spacing: -3px;
	                font-family: 'Lato', sans-serif;
	                font-size: 100px;
	                font-weight: 200;
	                margin-bottom: 0;
	            }
	        </style>
	</head>
	<body>
		<h2>Usuarios</h2>
		<?php if(is_array($all)): ?>
	        <div class="row">
	            <?php foreach($all as $user):?>
	                <div class="col-md-8">
	                    <?php echo $user['nombre']; ?> <?php echo $user['apellidos']; ?>
	                </div>
	            <?php endforeach; ?>
	        </div>
	    <?php endif; ?>
	</body>
	</html>